version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "4567:4567"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: password
      DATABASE_NAME: conference_db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: conference_db
    ports:
      - "3306:3306"